devices:
- credentials:
    password: ''
    username: admin
  description: MikroTik Edge
  driver: ros
  group: Edge
  hostname: 127.0.0.1
  id: mikrotik-edge-01
  port: 8728
  tags:
  - lab
  - mikrotik
  - routeros
  type: router
- credentials:
    password: ***REMOVED***
    username: admin
  description: ''
  driver: ros
  group: Edge
  hostname: 10.0.0.20
  id: mikrotik-edge-02
  port: 8728
  tags: []
  type: router
- credentials:
    password: ***REMOVED***
    username: doker
  description: MikroTik físico - API 8728
  driver: ros
  group: Edge
  hostname: 192.168.88.1
  id: mikrotik-prueba
  port: 8728
  tags: []
  type: router
- cli_port: 23
  cli_transport: telnet
  credentials:
    community: ***REMOVED***
    password: ''
    username: manager
  description: HP ProCurve 3400cl-24G — SNMP (telemetría) + Telnet (CLI legacy)
  driver: procurve
  group: null
  hostname: 192.168.1.10
  id: prueba hp pro curve
  noauth_telnet: true
  port: 161
  protocol: snmp
  tags: []
  type: switch
- cli_port: 23
  cli_transport: telnet
  credentials:
    community: public
    password: ''
    username: admin
  description: ''
  driver: snmp
  enable_password: ''
  group: null
  hostname: 192.168.1.30
  id: enterases
  netmiko_device_type: enterasys
  noauth_telnet: false
  port: 23
  protocol: snmp
  tags: []
  type: router
