name: "Agregar Peer BGP"
description: "Configura un nuevo peer BGP"
parameters:
  - local_as
  - peer_ip
  - remote_as
  - description
ios: |
  router bgp {{local_as}}
   neighbor {{peer_ip}} remote-as {{remote_as}}
   neighbor {{peer_ip}} description {{description}}
junos: |
  set protocols bgp group peers neighbor {{peer_ip}} peer-as {{remote_as}}
  set protocols bgp group peers neighbor {{peer_ip}} description {{description}}
eos: |
  router bgp {{local_as}}
   neighbor {{peer_ip}} remote-as {{remote_as}}
   neighbor {{peer_ip}} description {{description}}
